animalEvents/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from home import views

urlpatterns = [
    path('', include('home.urls')),
    path('home/', include('home.urls')),
    path('content/', include('content.urls')),
    path('user/', include('user.urls')),
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),

    path('hakkimizda/', views.hakkimizda, name='hakkimizda'),
    path('referanslar/', views.referanslar, name='referanslar'),
    path('iletisim/', views.iletisim, name='iletisim'),
    path('error/', views.error, name='error'),
    path('search/', views.content_search, name='content_search'),
    path('search_auto/', views.content_search_auto, name='content_search_auto'),
    path('logout/', views.logout_view, name='logout_view'),
    path('login/', views.login_view, name='login_view'),
    path('signup/', views.signup_view, name='signup_view'),
    path('sss/', views.faq, name='faq'),

    path('content/<int:id>/<slug:slug>/', views.contentdetail, name='contentdetail'),
    path('menu/<int:id>', views.menu, name='menu'),

]

if settings.DEBUG: #new
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

content/urls.py
from django.urls import path

from . import views

urlpatterns = [
    # ex: /product/
    path('', views.index, name='index'),
    path('addcomment/<int:id>', views.addcomment, name='addcomment')
    # ex: /polls/5/
   # path('<int:question_id>/', views.detail, name='detail'),

]

home/urls.py
from django.urls import path

from . import views

urlpatterns = [
    # ex: /home/    yani herhangi bir parametre girilmez ise home dizinine gidilsin
    path('', views.index, name='index'),
    # ex: /polls/5/
   # path('<int:question_id>/', views.detail, name='detail'),

]

content/models.py
from ckeditor.widgets import CKEditorWidget
from ckeditor_uploader.fields import RichTextUploadingField
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
from django.forms import ModelForm
from django.urls import reverse
from django.utils.safestring import mark_safe
from mptt.fields import TreeForeignKey
from mptt.models import MPTTModel
from django.forms import TextInput, Select, FileInput



class Menu(MPTTModel):
    STATUS = (  # açılan kutuda buranın gelmesini istiyoruz
        ('True', 'Evet'),
        ('False', 'Hayır'),
    )
    parent = TreeForeignKey('self', blank=True, null=True, related_name='children', on_delete=models.CASCADE) #model.CASCADE bir şey silineceği zaman ona bağlı şeyleri de silmeyi istediğimiz zaman kullanırız.
    title = models.CharField(max_length=100, unique=True) #charfield=uzunluk, alan türü
    link = models.CharField(max_length=100, blank=True)
    status = models.CharField(max_length=10, choices=STATUS)
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    class MPTTMeta:
        order_insertion_by = ['title']


    def __str__(self):
        full_path = [self.title]
        k = self.parent
        while k is not None:
            full_path.append(k.title)
            k = k.parent
        return ' / '.join(
            full_path[::-1])  # bunun amacı alt kategori olduğu sürece buluyor ve istediğimiz sıra ile bize getiriyor



TYPE = ( #global olarak çağırabilmek için dışarı aldım
        ('menu', 'menu'),
        ('haber', 'haber'),
        ('etkinlik', 'etkinlik'),
        ('duyuru', 'duyuru'),
    )

class Content(models.Model):
    STATUS = (  #açılan kutuda buranın gelmesini istiyoruz
        ('True', 'Evet'),
        ('False', 'Hayır'),
    )
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True) #usera içerik ekleme yetkisi verdiğimiz için bunu yazıyoruz
    menu = models.OneToOneField(Menu, null=True, blank=True, on_delete=models.CASCADE) #relation with menu table
    title = models.CharField(max_length=100) #charfield=uzunluk, alan türü
    keywords = models.CharField(blank=True, max_length=255)
    description = models.CharField(blank=True, max_length=255)
    image = models.ImageField(blank=True, upload_to='images/')
    detail = RichTextUploadingField()
    slug = models.SlugField(blank=True, max_length=100) #id yerine metin değişkeni ile çağırmak istersek buna slug denir
    type = models.CharField(max_length=20, choices=TYPE)
    status = models.CharField(max_length=10, choices=STATUS)
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    #pythonın görmemiz için bize bir şey döndürmesini istiyoruz
    def __str__(self):
       return self.title



    def image_tag(self):
        return mark_safe('<img src="{}" height="50"/>'.format(self.image.url))
    image_tag.short_description = 'Image'

    def get_absolute_url(self):
        return reverse('content_detail', kwargs={'slug': self.slug})  #otomatik slug olusturma




class ContentForm(ModelForm):
    class Meta:
        model = Content
        fields = ['type', 'title', 'slug', 'keywords', 'description', 'image', 'detail']  # bu elemanlar gözükecek
        widgets = {
            'type': Select(attrs={'class': 'input', 'placeholder': 'type'}, choices=TYPE),
            'title': TextInput(attrs={'class': 'input', 'placeholder': 'title'}),
            'slug': TextInput(attrs={'class': 'input', 'placeholder': 'slug'}),
            'keywords': TextInput(attrs={'class': 'input', 'placeholder': 'keywords'}),
            'description': TextInput(attrs={'class': 'input', 'placeholder': 'description'}),
            'image': FileInput(attrs={'class': 'input', 'placeholder': 'image'}),
            'detail': CKEditorWidget(),  #ckeditor input, widget içerisinde kullandığım için böyle yazıyorum
        }

class Images(models.Model):
    content = models.ForeignKey(Content, on_delete=models.CASCADE)
    title = models.CharField(max_length=50, blank=True) #charfield=uzunluk, alan türü, blank=true dersek boş geçmemize izin verir
    image = models.ImageField(blank=True, upload_to='images/')

    def __str__(self):
        return self.title

    def image_tag(self):
        return mark_safe('<img src="{}" height="50"/>'.format(self.image.url))
    image_tag.short_description = 'Image'


class ContentImageForm(ModelForm):   #eğer bir validation yani kontrol yapmak için kullanmak istersek ya da çağırmak istersek diye form yaptık
    class Meta:
        model =Images
        fields = ['title', 'image']


class Comment(models.Model):
    STATUS = (  # açılan kutuda buranın gelmesini istiyoruz
        ('New', 'Yeni'),
        ('True', 'Evet'),
        ('False', 'Hayır'),
    )
    content = models.ForeignKey(Content, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    subject = models.CharField(max_length=50)
    comment = models.TextField(max_length=200, blank=True)
    status = models.CharField(max_length=10, choices=STATUS, default='New')
    ip = models.CharField(max_length=20, blank=True)
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.subject

class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ['subject', 'comment']

home/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class SearchForm(forms.Form):
    query = forms.CharField(label='Search', max_length=100)  #query nesnesi ekledim form da böyle bir şey olmadığı için


class SignUpForm(UserCreationForm):
    username = forms.CharField(max_length=30, label='User Name :')
    email = forms.EmailField(max_length=200, label='Email :')
    first_name = forms.CharField(max_length=100, help_text='First Name', label='First Name :')
    last_name = forms.CharField(max_length=100, help_text='Last Name', label='Last Name :')


    class Meta:
        model = User
        fields = ('username', 'email', 'first_name', 'last_name', 'password1', 'password2')

content/views.py
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render

# Create your views here.
from content.models import CommentForm, Comment


def index(request):
      return HttpResponse(" Content Page")

@login_required(login_url='/login') #check login, login olup olmadığını kontrol ediyorum

def addcomment(request, id):
      url = request.META.get('HTTP_REFERER')  # get last url
      if request.method == 'POST': #form post edildiyse
            form = CommentForm(request.POST)
            if form.is_valid():
                  current_user = request.user #Access User Session Information

                  data = Comment() #model ile bağlantı kur
                  data.user_id = current_user.id
                  data.content_id = id
                  data.subject = form.cleaned_data['subject']
                  data.comment = form.cleaned_data['comment']
                  data.ip = request.META.get('REMOTE_ADDR') #Client computer ip address
                  data.save()  #veritabanına  kaydet
                  messages.success(request, 'Yorumunuz başarı ile gönderilmiştir. Teşekkür ederiz!')
                  return HttpResponseRedirect(url)

            messages.warning(request, 'Yorumunuz kaydedilmedi. Lütfen konrol ediniz.')
            return HttpResponse('Kaydedilme İşlemi Gerçekleşmedi')

home/views.py
from django.contrib import messages
from django.contrib.auth import logout, authenticate, login
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render

# Create your views here.
from pandas._libs import json

from content.models import Content, Images, Menu, Comment
from home.forms import SearchForm, SignUpForm
from home.models import Setting, ContactFormu, ContactFormMessage, FAQ, UserProfile


def index(request):
    setting = Setting.objects.get(pk=1)
    menu = Menu.objects.all()
    sliderdata = Content.objects.filter(status='True').order_by('-id')[:4]  # tüm verileri getiriyoruz, 4 tanesini gösteriyorum
    activitydata = Content.objects.filter(type='etkinlik', status='True').order_by('-id')[:3]
    announcementdata = Content.objects.filter(type='duyuru', status='True').order_by('?')[:3]
    newsdata = Content.objects.filter(type='haber', status='True').order_by('?')[:3]  # ? random olarak getirir
    context = {'setting': setting,
               'page': 'home',
               'sliderdata': sliderdata,
               'activitydata': activitydata,
               'announcementdata': announcementdata,
               'newsdata': newsdata,
               'menu': menu,

               }
    return render(request, 'index.html', context)


def hakkimizda(request):
    setting = Setting.objects.get(pk=1)
    menu = Menu.objects.all()
    context = {'setting': setting, 'menu': menu}
    return render(request, 'hakkimizda.html', context)


def referanslar(request):
    setting = Setting.objects.get(pk=1)
    menu = Menu.objects.all()
    context = {'setting': setting, 'menu': menu}
    return render(request, 'referanslarimiz.html', context)


def iletisim(request):
    if request.method == 'POST':  # form post edildiyse
        form = ContactFormu(request.POST)
        if form.is_valid():
            data = ContactFormMessage()  # model ile bağlantı kur
            data.name = form.cleaned_data['name']  # fromdan bilgiyi al
            data.email = form.cleaned_data['email']
            data.subject = form.cleaned_data['subject']
            data.message = form.cleaned_data['message']
            data.ip = request.META.get('REMOTE_ADDR')  # GÖNDERENİN İP ADRESİNİ ALIYORUM, remote_addr olarak alıp ipye atıyorum
            data.save()  # veritabanına kaydet
            messages.success(request, "Mesajınız başarı ile gönderilmiştir. Teşekkür ederiz")  # tek kullanımlık mesaj alanı
            return HttpResponseRedirect('/iletisim')

    setting = Setting.objects.get(pk=1)
    form = ContactFormu()
    menu = Menu.objects.all()
    context = {'setting': setting, 'form': form, 'menu': menu}
    return render(request, 'iletisim.html', context)


def menu(request, id):
    try:
        content = Content.objects.get(menu_id=id)
        link = '/content/' + str(content.id) + '/menu'  # menu hangi içerikteyse git onu bul ve calıstır
        return HttpResponseRedirect(link)
    except:
        messages.warning(request, "Hata ! İlgili içerik bulunamadı ")
        link = '/error'
        return HttpResponseRedirect(link)



def contentdetail(request, id, slug):
    comments = Comment.objects.filter(content_id=id, status='True')
    menu = Menu.objects.all()
    content = Content.objects.get(pk=id)
    try:

        images = Images.objects.filter(content_id=id)
        context = {
            'content': content,
            'images': images,
            'menu': menu,
            'comments': comments,

        }
        return render(request, 'contents_detail.html', context)
    except:
        messages.warning(request, "Hata ! İlgili içerik bulunamadı ")
        link = '/error'
        return HttpResponseRedirect(link)


def error(request):
    menu = Menu.objects.all()
    context = {
        'menu': menu,
    }
    return render(request, 'error_page.html', context)


def content_search(request):
    if request.method == 'POST':  #check form post
        form = SearchForm(request.POST)
        if form.is_valid():
            content = Content.objects.all()
            menu= Menu.objects.all()
            query = form.cleaned_data['query']  #formdan bilgiyi al
            contents = Content.objects.filter(title__icontains=query) #Select * from content where title like %query%    #icontains=büyük küçük harf dikkate alma demek
            context = {
                'content': content,
                'menu': menu,
                'contents': contents,
                }
            return render(request, 'contents_search.html', context)

    return HttpResponseRedirect('/')

def content_search_auto(request):
    if request.is_ajax():
        q = request.GET.get('term', '')
        content = Content.objects.filter(title__icontains=q)
        results = []
        for rs in content:
            content_json = {}
            content_json = rs.title
            results.append(content_json)
        data = json.dumps(results)
    else:
        data = 'fail'
    mimetype = 'application/json'
    return HttpResponse(data, mimetype)



def logout_view(request):
    logout(request)
    return HttpResponseRedirect('/')   #anasayfaya gitsin



def login_view(request):
    if request.method == 'POST':  # check form post
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            # Redirect to a success page.
            return HttpResponseRedirect('/')  #  başarılı olursa anasayfaya gitsin

        else:
            # Return an 'invalid login' error message.
            messages.warning(request, "Login Hatası ! Kullanıcı adı veya şifre yanlış")  # tek kullanımlık mesaj alanı
            return HttpResponseRedirect('/login')
    menu = Menu.objects.all()
    context = {
            'menu': menu,
        }
    return render(request, 'login.html', context)



def signup_view(request):
    if request.method == 'POST':  # check form post
        form = SignUpForm(request.POST)
        if form.is_valid():  #if else yapmıyoruz burada validation zaten uygun mu değil mi kontrol ediyor her şeyi
            form.save()
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=password)
            login(request, user)
            #Create data in profile table for user
            current_user =request.user
            data = UserProfile()
            data.user_id = current_user.id
            data.image = "images/users/user.png"
            data.save()
            messages.success(request, "Hoşgeldiniz!")  # tek kullanımlık mesaj alanı
            return HttpResponseRedirect("/")

    form = SignUpForm()
    menu = Menu.objects.all()
    context = {
        'menu': menu,
        'form': form,
    }
    return render(request, 'signup.html', context)


def faq(request):
    menu = Menu.objects.all()
    faq = FAQ.objects.all().order_by('contentnumber')
    context = {
        'menu': menu,
        'faq': faq,

    }
    return render(request, 'faq.html', context)

home/templates/contents.html
{% extends "homebase.html" %} #burada diyorum ki ben bu sayfada homebase bağlı çalışacağım

{% block title %} {{ categorydata.title }} Contents {% endblock %}  #title olan bloğa bunu yaz
{% block keywords %} {{ categorydata.keywords }} {% endblock %}
{% block description %} {{ categorydata.description }} {% endblock %}

{% block head %}
    <link rel='shortcut icon' type="image/x-icon"  href="{{setting.icon.url}}" />
{% endblock %}



{% block content %}
        <!-- BREADCRUMB -->
        <div id="breadcrumb" class="hoc clear">

           <ul>
              <li><a href="/">Anasayfa</a></li>
               <li><a class="active">{{ content.title }} </a></li>
            </ul>

          </div>

        <!-- /BREADCRUMB-->

        <!--section -->
      <div class="wrapper row3">
        <main class="hoc container clear">

    <ul class="nospace group overview">

     {% for rs in content %}
      <li class="one_third">
        <article>
          <h6 class="heading"> {{rs.title }} </h6>
          <a href="#"><img src="{{ rs.image.url }} " alt=""></a>
          <ul class="nospace meta">
            <li><i class="fa fa-user"></i> <a href="#"> {{ rs.content }}</a></li>
          </ul>
          <p>{{ rs.description }}</p>
          <footer class="nospace"><a class="btn" href="/contents_detail/{{ rs.id }}/{{ rs.slug }}">Devamı.. &raquo;</a></footer>
        </article>
      </li>
   {% endfor %}



    </ul>
        </main>

        </div>
        <!--section -->
{% endblock %}

home/templates/contents_detail.html
{% extends "homebase.html" %} #burada diyorum ki ben bu sayfada homebase bağlı çalışacağım

{% block title %} {{ content.title }} {% endblock %}  #title olan bloğa bunu yaz
{% block keywords %} {{ content.keywords }} {% endblock %}
{% block description %} {{ content.description }} {% endblock %}
{% block head %}
    <link rel='shortcut icon' type="image/x-icon"  href="{{setting.icon.url}}" />

{% endblock %}

{% block content %}
        <!-- BREADCRUMB -->

        <div id="breadcrumb" class="hoc clear">

           <ul>
               <li><a href="/">Anasayfa</a></li>
               <li><a class="active">{{ content.title }} </a></li>
            </ul>

          </div>

        <!-- /BREADCRUMB-->

        <!--section -->
      <div class="wrapper row3">
        <main class="hoc container clear">
          <div class="content">
              <h1> {{ content.title }}</h1>

              <img src="{{ content.image.url }}" alt="" style="height: 300px">

      <p>{{ content.description }}</p>

      <p>{{ content.detail | safe }}</p>

       <br><br><br>
              <div class="hoc clear">
                  <figure id="introblocks">
                      <ul class="nospace group">
                          <li class="one_third first"><a href="{{ content.image.url }}" data-lightbox="mygallery"><img src="{{ content.image.url }}" alt="" style="height: 200px"></a></li>
                          {% for rs in images %} <!-- İçerik resim galerisi-->
                          <li class="one_third"><a href="{{ rs.image.url }}" data-lightbox="mygallery"><img src="{{ rs.image.url }}" alt="" style="height: 200px"></a></li>
                          {% endfor %}

                      </ul>
                  </figure>
              </div>


            <!-- yorum vs eklenecek-->
     <div id="comments">
        <h2>Yorumlar</h2>
        <ul>
            {% for rs in comments %}
               <li>
                <article>
                  <header>
                    <figure class="avatar"><i class="fa fa-user-o"></i></figure>
                    <address>
                    By <a href="#"><b>{{ rs.user }}</b></a>
                    </address>
                    <time datetime="2045-04-06T08:15+00:00">{{ rs.create_at }}</time>
                  </header>
                  <div class="comcont">
                      <b> {{rs.subject}} </b>
                      <br>
                        {{rs.comment}}
                  </div>
                </article>
               </li>
           {% endfor %}
            <li>
            <article>

            {% if messages %}
                {% for message in messages %}
                  <div class="alert alert-{{message.tags}}" role="alert" >
                    <p> {{ message }} </p>
                  </div>
                {% endfor %}
            {% endif %}

            </article>
          </li>


        </ul>


        <h2>Bir yorum yaz</h2>
        <form action="/content/addcomment/{{content.id}}" method="post">
            {% csrf_token %}
          <div class="one_third first">
            <label for="id_subject">Konu <span>*</span></label>
            <input type="text" name="subject" id="id_subject" placeholder="Konu" value="" size="22" required>
          </div>

          <div class="block clear">
            <label for="id_comment">Sizin yorumunuz</label>
            <textarea name="comment" id="id_comment" cols="25" rows="10" placeholder="Sizin görüşünüz"></textarea>
          </div>
          <div>
           {% if user.id is not None %}
            <input type="submit" name="submit" value="Yorumu Kaydet">
           {% else %}
              Yorum Eklemek için  <a href="/login"> Login </a>  olunuz!
           {% endif %}
          </div>
        </form>
      </div>
      </div>
        </main>

        </div>
        <!--section -->
{% endblock %}

home/templates/contents_search.html
{% extends "homebase.html" %} #burada diyorum ki ben bu sayfada homebase bağlı çalışacağım

{% block title %} Content Search Results {% endblock %}  #title olan bloğa bunu yaz
{% block keywords %} {{ content.keywords }} {% endblock %}
{% block description %} {{ content.description }} {% endblock %}
{% block head %}
    <link rel='shortcut icon' type="image/x-icon"  href="{{setting.icon.url}}" />
{% endblock %}

{% block content %}
        <!-- BREADCRUMB -->
        <div id="breadcrumb" class="hoc clear">

           <ul>
              <li><a href="/">Anasayfa</a></li>
               <li><a class="active">{{search.title}}</a></li>
            </ul>

          </div>

        <!-- /BREADCRUMB-->

        <!--section -->
      <div class="wrapper row3">
        <main class="hoc container clear">

         <div class="scrollable">
            <table>
              <thead>
                <tr>
                  <th>Image</th>
                  <th>Content Name</th>
                  <th>Description</th>
                  <th>Type</th>
                </tr>
              </thead>
              <tbody>
              {% for rs in contents %}
                <tr>
                  <td><a href="/content/{{rs.id}}/{{rs.slug}}"><img src="{{ rs.image.url }}" style="height:200px, width:200px" alt=""></a></td>
                  <td><h4><a href="/content/{{rs.id}}/{{rs.slug}}/{{rs.title}}"></a> {{rs.title}} </h4></td>
                  <td><a href="/content/{{rs.id}}/{{rs.slug}}/{{rs.description}}"></a> {{rs.description}}</td>
                  <td><a href="/content/{{rs.content_id}}/{{rs.content_slug}}">{{rs.type}}</a></td>
                </tr>
              {% endfor %}
              </tbody>
            </table>
      </div>
        </main>

        </div>
        <!--section -->
{% endblock %}

home/templates/error_page.html
{% extends "homebase.html" %} #burada diyorum ki ben bu sayfada homebase bağlı çalışacağım

{% block title %} Hakkımızda-{{ setting.company }} {% endblock %}  #title olan bloğa bunu yaz
{% block keywords %} {{ setting.keywords }} {% endblock %}
{% block description %} {{ setting.description }} {% endblock %}
{% block head %}
    <link rel='shortcut icon' type="image/x-icon"  href="{{setting.icon.url}}" />
{% endblock %}

{% block content %}
        <!-- BREADCRUMB -->
        <div id="breadcrumb" class="hoc clear">

           <ul>
              <li><a href="/">Anasayfa</a></li>
               <li><a class="active">Hata</a></li>
            </ul>

          </div>

        <!-- /BREADCRUMB-->

        <!--section -->
      <div class="wrapper row3">
        <main class="hoc container clear">
            <div align="center">
                <H1>ARADIĞINIZ İÇERİK BULUNAMADI</H1>
                <H3><a href="/">Anasayfaya Dön</a></H3>
            </div>
        </main>

        </div>
        <!--section -->
{% endblock %}

home/templates/faq.html
{% extends "homebase.html" %} #burada diyorum ki ben bu sayfada homebase bağlı çalışacağım

{% block title %} Sıkça Sorulan Sorular {% endblock %}  #title olan bloğa bunu yaz
{% block keywords %}  {% endblock %}
{% block description %}  {% endblock %}
{% block head %}
    <link rel='shortcut icon' type="image/x-icon"  href="{{setting.icon.url}}" />
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
      <script>
  $( function() {
    $( "#accordion" ).accordion({
      collapsible: true
    });
  } );
  </script>

{% endblock %}

{% block content %}
        <!-- BREADCRUMB -->
        <div id="breadcrumb" class="hoc clear">

           <ul>
              <li><a href="/">Anasayfa</a></li>
               <li><a class="active">Sıkça Sorulan Sorular</a></li>
            </ul>

          </div>

        <!-- /BREADCRUMB-->

        <!--section -->
      <div class="wrapper row3">
        <main class="hoc container clear">

            <div id="accordion">
                {% for rs in faq %}
              <h3> {{ rs.question }}</h3>
              <div>
                <p>{{ rs.answer }}</p>
              </div>
              {% endfor %}
            </div>

        </main>

        </div>
        <!--section -->
{% endblock %}

home/templates/footer.html
{% load static %}

<div class="wrapper row4">

  <footer id="footer" class="hoc clear">
    <div class="third_quarter" >
      <h6 class="heading">HACHIKO- Hayvanları Koruma Derneği</h6>
      <ul class="nospace btmspace-30 linklist contact">
        <li><i class="fa fa-map-marker"></i>
          <address>
            Kızılay Mahallesi, Şehit Adem Yavuz Sokak, No: 4/8 - Çankaya / Ankara
          </address>
        </li>
        <li><i class="fa fa-phone"></i> 0312 418 08 98</li>
        <li><i class="fa fa-envelope-o"></i> iletisim@hachiko.org</li>
      </ul>
      <ul class="faico clear">
        <li><a class="faicon-facebook" href="#"><i class="fa fa-facebook"></i></a></li>
        <li><a class="faicon-twitter" href="#"><i class="fa fa-twitter"></i></a></li>
        <li><a class="faicon-dribble" href="#"><i class="fa fa-dribbble"></i></a></li>
        <li><a class="faicon-linkedin" href="#"><i class="fa fa-linkedin"></i></a></li>
      </ul>
    </div>

  </footer>

</div>

<div class="wrapper row5">
  <div class="wrapper bgded overlay coloured" style="background-color:#f06292">
  <div id="copyright" class="hoc clear">
   <p class="fl_left"><br><a href="/" style="background-color:transparent">Anasayfa</a>| <a href="/iletisim" style="background-color:transparent">İletişim</a> | <a href="/hakkimizda" style="background-color:transparent">Hakkımızda</a> </p>
    <br><br><br><br><br>
    <p class="fl_left">Copyright &copy; 2020 - Tüm hakları saklıdır. - HACHIKO -Türkiye Hayvanları Koruma Derneği.<br>
                        Kamu yararına çalışan dernek statüsündedir.</p>

    <p class="fl_right">Template by <a target="_blank" href="https://www.os-templates.com/" title="Free Website Templates" style="background-color:transparent">OS Templates</a></p>
  </div>
  </div>
</div>

<a id="backtotop" href="#top"><i class="fa fa-chevron-up"></i></a>

home/templates/index.html
{% extends "homebase.html" %} #burada diyorum ki ben bu sayfada homebase bağlı çalışacağım

{% block title %} {{ setting.title }} {% endblock %}  #title olan bloğa bunu yaz
{% block keywords %} {{ setting.keywords }} {% endblock %}
{% block description %} {{ setting.description }} {% endblock %}

{% block head %}
    <link rel='shortcut icon' type="image/x-icon"  href="{{setting.icon.url}}" />
{% endblock %}



{% block slider %} {% include "slider.html" %} {% endblock %}
{% block content %} {% include "content.html" %} {% endblock %}

home/templates/slider.html
{% load static %}
<div class="bgded overlay light" >
 <div id="pageintro" class="hoc clear">
    <div class="fldexslier basicslider">
      <ul class="slides">

        <!--banner-->
        {% for rs in sliderdata %} <!--rs=record set yani satır-->
        <li>
         <article>
            <img src="{{ rs.image.url }} " alt="">
            <p>{{ rs.title }}</p>
               <footer class="nospace"><a class="btn" href="/content/{{ rs.id }}/{{ rs.slug }}">İncele.. &raquo;</a></footer>
          </article>
        </li>
        {% endfor %}
         <!--/banner-->

         <!--Artık dinamik yaptığımız için diğerlerini siliyoruz-->
      </ul>

    </div>
  </div>
</div>