animalEvents/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from home import views

urlpatterns = [
    path('', include('home.urls')),
    path('home/', include('home.urls')),
    path('content/', include('content.urls')),
    path('user/', include('user.urls')),
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),

    path('hakkimizda/', views.hakkimizda, name='hakkimizda'),
    path('referanslar/', views.referanslar, name='referanslar'),
    path('iletisim/', views.iletisim, name='iletisim'),
    path('error/', views.error, name='error'),
    path('search/', views.content_search, name='content_search'),
    path('search_auto/', views.content_search_auto, name='content_search_auto'),
    path('logout/', views.logout_view, name='logout_view'),
    path('login/', views.login_view, name='login_view'),
    path('signup/', views.signup_view, name='signup_view'),
    path('sss/', views.faq, name='faq'),

    path('content/<int:id>/<slug:slug>/', views.contentdetail, name='contentdetail'),
    path('menu/<int:id>', views.menu, name='menu'),

]

if settings.DEBUG: #new
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path

from . import views

urlpatterns = [
    # ex: /home/    yani herhangi bir parametre girilmez ise home dizinine gidilsin
    path('', views.index, name='index'),
    # ex: /polls/5/
   # path('<int:question_id>/', views.detail, name='detail'),

]

user/urls.py
from django.urls import path

from . import views

urlpatterns = [
    # ex: /product/
    path('', views.index, name='index'),
    path('update/', views.user_update, name='user_update'),
    path('password/', views.change_password, name='change_password'),
    path('comments/', views.comments, name='comments'),
    path('deletecomment/<int:id>', views.deletecomment, name='deletecomment'),
    path('addcontent/', views.addcontent, name='addcontent'),
    path('contents/', views.contents, name='contents'),    #listelemek için
    path('contentedit/<int:id>', views.contentedit, name='contentedit'),
    path('contentdelete/<int:id>', views.contentdelete, name='contentdelete'),
    path('contentaddimage/<int:id>', views.contentaddimage, name='contentaddimage'),

    # ex: /polls/5/
   # path('<int:question_id>/', views.detail, name='detail'),

]

home/models.py
from ckeditor_uploader.fields import RichTextUploadingField
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
from django.forms import ModelForm, TextInput, Textarea
from django.utils.safestring import mark_safe


class Setting(models.Model):
    STATUS = (  # açılan kutuda buranın gelmesini istiyoruz
        ('True', 'Evet'),
        ('False', 'Hayır'),
    )
    title = models.CharField(max_length=100) #charfield=uzunluk, alan türü
    keywords = models.CharField(max_length=255)
    description = models.CharField(max_length=255)
    company = models.CharField(max_length=50)
    address = models.CharField(blank=True, max_length=100)
    phone = models.CharField(blank=True, max_length=15)
    fax = models.CharField(blank=True, max_length=15)
    email = models.CharField(blank=True, max_length=50)
    smtpserver = models.CharField(blank=True, max_length=20)
    smtpemail = models.CharField(blank=True, max_length=20)
    smtppassword = models.CharField(blank=True, max_length=10)
    smtpport = models.CharField(blank=True, max_length=5)
    icon = models.ImageField(blank=True, upload_to='images/')
    facebook = models.CharField(blank=True, max_length=50)
    instagram = models.CharField(blank=True, max_length=50)
    twitter = models.CharField(blank=True, max_length=50)
    aboutus = RichTextUploadingField(blank=True)
    contact = RichTextUploadingField(blank=True)
    references = RichTextUploadingField(blank=True)
    status = models.CharField(max_length=10, choices=STATUS)
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    # pythonın görmemiz için bize bir şey döndürmesini istiyoruz
    def __str__(self):
        return self.title

class ContactFormMessage(models.Model):
    STATUS =(
        ('New', 'New'),
        ('Read', 'Read'),
        ('Closed', 'Closed'),
    )
    name = models.CharField(blank=True, max_length=20)
    email = models.CharField(blank=True, max_length=50)
    subject = models.CharField(blank=True, max_length=50)
    message = models.CharField(blank=True, max_length=255)
    status = models.CharField(max_length=10,choices=STATUS,default='New')
    ip = models.CharField(blank=True, max_length=20) #gönderenin ip adresi
    note = models.CharField(blank=True, max_length=100) #admin notu
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    # pythonın görmemiz için bize bir şey döndürmesini istiyoruz
    def __str__(self):
        return self.name


class ContactFormu(ModelForm):
    class Meta:
        model = ContactFormMessage  #bu forma ait
        fields = ['name', 'email', 'subject', 'message']  #bu elemanlar gözükecek
        widgets = {
            'name': TextInput(attrs={'class': 'input', 'placeholder': 'Name & Surname'}),
            'subject': TextInput(attrs={'class': 'input', 'placeholder': 'Subject'}),
            'email': TextInput(attrs={'class': 'input', 'placeholder': 'Email Address'}),
            'message': TextInput(attrs={'class': 'input', 'placeholder': 'Your Message', 'rows': '5'}),

        }



class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)  #ilişki demektir user_id için bir tane oluşturuyor
    email = models.EmailField(blank=True, max_length=200)
    phone = models.CharField(blank=True, max_length=20)
    address = models.CharField(blank=True, max_length=150)
    city = models.CharField(blank=True, max_length=20)
    country = models.CharField(blank=True, max_length=20)
    image = models.ImageField(blank=True, upload_to='images/users/')

    def __str__(self):
        return self.user.username

    def user_name(self):
        return self.user.first_name + ' ' + self.user.last_name + ' ' + '['+self.user.username + ']'

    def image_tag(self):
        return mark_safe('<img src="{}" height="50"/>'.format(self.image.url))

    image_tag.short_description = 'Image'

class UserProfileFormu(ModelForm):
    class Meta:
        model = UserProfile  #bu forma ait
        fields = ['phone', 'email', 'address', 'city', 'country', 'image']  #bu elemanlar gözükecek




class FAQ(models.Model):   #sık sorulan sorular bolumu
    STATUS = (  # açılan kutuda buranın gelmesini istiyoruz
        ('True', 'Evet'),
        ('False', 'Hayır'),
    )
    contentnumber =models.IntegerField()
    question = models.CharField(max_length=150) #charfield=uzunluk, alan türü
    answer = models.TextField() #sınırlandırmayı kaldırdım o zamanda tekrar migrations yapmam lazım
    status = models.CharField(max_length=10, choices=STATUS)
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    # pythonın görmemiz için bize bir şey döndürmesini istiyoruz
    def __str__(self):
        return self.question

user/models.py
from django.db import models

# Create your models here.

user/forms.py
from django import forms
from django.contrib.auth.forms import UserChangeForm
from django.contrib.auth.models import User
from django.forms import TextInput, Select, FileInput

from home.models import UserProfile


class UserUpdateForm(UserChangeForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'first_name', 'last_name')  # bu elemanlar gözükecek
        widgets = {
            'username': TextInput(attrs={'class': 'input', 'placeholder': 'username'}),
            'email': TextInput(attrs={'class': 'input', 'placeholder': 'email'}),
            'first_name': TextInput(attrs={'class': 'input', 'placeholder': 'first_name'}),
            'last_name': TextInput(attrs={'class': 'input', 'placeholder': 'last_name'}),

        }
CITY = [
    ('Kocaeli', 'Kocaeli'),
    ('İstanbul', 'İstanbul'),
    ('Ankara', 'Ankara'),
    ('İzmir', 'İzmir'),

]
class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('phone', 'address', 'city', 'country', 'image')  # bu elemanlar gözükecek
        widgets = {
            'phone': TextInput(attrs={'class': 'input', 'placeholder': 'phone'}),
            'address': TextInput(attrs={'class': 'input', 'placeholder': 'address'}),
            'city': Select(attrs={'class': 'input', 'placeholder': 'city'}, choices=CITY),
            'country': TextInput(attrs={'class': 'input', 'placeholder': 'country'}),
            'image': FileInput(attrs={'class': 'input', 'placeholder': 'image'}), #dosya upload etmek için fileInput yazdık
        }

user/views.py
from django.contrib import messages
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import PasswordChangeForm
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect

# Create your views here.
from content.models import Menu, Content, ContentForm, Comment, Images, ContentImageForm
from home.models import UserProfile
from user.forms import UserUpdateForm, ProfileUpdateForm


def index(request):
    menu = Menu.objects.all()
    current_user = request.user  # Access User Session Information
    profile = UserProfile.objects.get(user_id=current_user.id)
    context = {
        'menu': menu,
        'profile': profile,
    }
    return render(request, 'user_profile.html', context)


@login_required(login_url='/login')  # check login, login olup olmadığını kontrol ediyorum
def user_update(request):
    if request.method == 'POST':
        user_form = UserUpdateForm(request.POST, instance=request.user)  # request.user is user data
        profile_form = ProfileUpdateForm(request.POST, request.FILES, instance=request.user.userprofile)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success(request, 'Profiliniz başarı ile güncellendi !')
            return redirect('/user')

    else:
        menu = Menu.objects.all()
        current_user = request.user  # Access user session information
        user_form = UserUpdateForm(instance=request.user)  # userla ilişki kursun diyorum
        profile_form = ProfileUpdateForm(instance=request.user.userprofile)  # "userprofile" model -> OneToOneField relatinon with user =>yani user tablosundaki userprofileı onetoone ilişkisine göre getir diyorum
    context = {
        'menu': menu,
        'user_form': user_form,
        'profile_form': profile_form,
    }
    return render(request, 'user_update.html', context)


@login_required(login_url='/login')  # check login, login olup olmadığını kontrol ediyorum
def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)  # important
            messages.success(request, 'Şifreniz başarılı bir şekilde değiştirildi !')
            return HttpResponseRedirect("/user")
        else:
            messages.error(request, 'Hata ! Lütfen kontrol ederek tekrar deneyiniz.<br>' + str(
                form.errors))  # bunu buraya yazabilmemiz için stringe çevirmemiz lazım on yüzden str yazıyoruz
            return HttpResponseRedirect('/user/password')

    else:
        menu = Menu.objects.all()
        form = PasswordChangeForm(request.user)  # sadece mevcut kullancının bilgilerini al getir
        return render(request, 'change_password.html', {
            'form': form, 'menu': menu
        })



@login_required(login_url='/login')  # check login, login olup olmadığını kontrol ediyorum
def comments(request):
    menu = Menu.objects.all()
    current_user = request.user  # Access User Session Information
    comments = Comment.objects.filter(user_id=current_user.id)
    context = {
        'menu': menu,
        'comments': comments,
    }
    return render(request, 'user_comments.html', context)




@login_required(login_url='/login')  # check login, login olup olmadığını kontrol ediyorum
def deletecomment(request,id):
    current_user = request.user
    Comment.objects.filter(id=id, user_id=current_user.id).delete()
    messages.success(request, 'Yorum silindi...')
    return HttpResponseRedirect("/user/comments")


@login_required(login_url='/login')  # check login, login olup olmadığını kontrol ediyorum
def addcontent(request):
    if request.method == 'POST':
        form = ContentForm(request.POST, request.FILES)  # fileupload varsa request.FILES yapmazsak formumuz çalışmaz
        if form.is_valid():
            current_user = request.user
            data = Content()  # model ile bağlantı kur
            data.user_id = current_user.id
            data.title = form.cleaned_data['title']
            data.keywords = form.cleaned_data['keywords']
            data.description = form.cleaned_data['description']
            data.image = form.cleaned_data['image']
            data.type = form.cleaned_data['type']
            data.slug = form.cleaned_data['slug']
            data.detail = form.cleaned_data['detail']
            data.status = 'False'
            data.save()  # veritabanına kaydet
            messages.success(request, 'İçeriğiniz başarılı bir şekilde eklendi !')
            return HttpResponseRedirect("/user/contents")
        else:
            messages.error(request, 'İçerik Form Hatası : ' + str(
                form.errors))  # bunu buraya yazabilmemiz için stringe çevirmemiz lazım on yüzden str yazıyoruz
            return HttpResponseRedirect('/user/addcontent')
    else:
        menu = Menu.objects.all()
        form = ContentForm()  # content form ile ilişki kuruyorum
        context = {
            'form': form,
            'menu': menu
        }
        return render(request, 'user_addcontent.html', context)





@login_required(login_url='/login')  # check login, login olup olmadığını kontrol ediyorum
def contents(request):
    menu = Menu.objects.all()
    current_user = request.user
    contents = Content.objects.filter(user_id=current_user.id)  # mevcut userın contentlerini çağırıyorum
    context = {
        'menu': menu,
        'contents': contents,
    }
    return render(request, 'user_contents.html', context)




@login_required(login_url='/login')  # check login, login olup olmadığını kontrol ediyorum
def contentedit(request,id):
    content = Content.objects.get(id=id) #mevcut içeriğin id'sini gönderiyorum
    if request.method == 'POST':
        form = ContentForm(request.POST, request.FILES, instance=content)  # fileupload varsa request.FILES yapmazsak formumuz çalışmaz
        if form.is_valid():
            form.save()  # veritabanına kaydet
            messages.success(request, 'İçeriğiniz başarılı bir şekilde güncellendi !')
            return HttpResponseRedirect("/user/contents")  #hata yoksa listeye gönder
        else:
            messages.error(request, 'İçerik Form Hatası : ' + str(form.errors))  # bunu buraya yazabilmemiz için stringe çevirmemiz lazım on yüzden str yazıyoruz
            return HttpResponseRedirect('/user/contentedit/' + str(id)) #id'yi tekrar oluşturmam lazım
    else:
        menu = Menu.objects.all()
        form = ContentForm(instance=content)  # content form ile ilişki kuruyorum, sorgulanan contentle formu dolduruyorum
        context = {
            'form': form,
            'menu': menu
        }
        return render(request, 'user_addcontent.html', context)



@login_required(login_url='/login')  # check login, login olup olmadığını kontrol ediyorum
def contentdelete(request,id):
    current_user = request.user
    Content.objects.filter(id=id, user_id=current_user.id).delete()
    messages.success(request, 'İçerik silindi...')
    return HttpResponseRedirect("/user/contents")


def contentaddimage(request,id):
    if request.method == 'POST':
        lasturl = request.META.get('HTTP_REFERER') #post etmeden önceki url'i alsın diye bunu yaptım yani açılan pencerede formu göndermeden öndeki açılan sayfa
        form = ContentImageForm(request.POST, request.FILES)  # fileupload varsa request.FILES yapmazsak formumuz çalışmaz
        if form.is_valid():
            data = Images()  # model ile bağlantı kur
            data.title = form.cleaned_data['title']
            data.content_id = id
            data.image = form.cleaned_data['image']
            data.save()  # veritabanına kaydet
            messages.success(request, 'Fotoğrafınız başarılı bir şekilde yüklendi !')
            return HttpResponseRedirect(lasturl)
        else:
            messages.warning(request, 'Form Hatası : ' + str(form.errors))  # bunu buraya yazabilmemiz için stringe çevirmemiz lazım on yüzden str yazıyoruz
            return HttpResponseRedirect(lasturl)
    else:
        content = Content.objects.get(id=id)
        images = Images.objects.filter(content_id=id)
        form = ContentImageForm()
        context = {
            'content': content,
            'images': images,
            'form': form,
        }
        return render(request, 'content_gallery.html', context)

user/templates/change_password.html
{% extends "homebase.html" %} #burada diyorum ki ben bu sayfada homebase bağlı çalışacağım

{% block title %} Şifre Değiştirme {% endblock %}  #title olan bloğa bunu yaz
{% block keywords %} {{ setting.keywords }} {% endblock %}
{% block description %} {{ setting.description }} {% endblock %}

{% block head %}
    <link rel='shortcut icon' type="image/x-icon"  href="{{setting.icon.url}}" />
{% endblock %}



{% block content %}
        <!-- BREADCRUMB -->
         <div id="breadcrumb" class="hoc clear">

           <ul>
              <li><a href="/">Anasayfa</a></li>
               <li><a class="active">Şifre Değitirme</a></li>
            </ul>

          </div>
        </div>
        <!-- /BREADCRUMB-->

        <!--section -->
           <div class="wrapper row1">
        <main class="hoc container clear">
             <div class="one_quarter">
                  <h6 class="heading">Şifre Değitirme</h6>

                   {% if messages %}  <!--sistem mesajları böyle kullanılır eğer bir mesaj varsa mesajın türüne göre ekrana yazıyor-->
                     {% for message in messages %}
                         <div style="color:#d43f3a; font-size:medium">
                             {{ message|safe  }}  <!--Bu uyarılar html tagları içeiryor bu yüzden safe yazdık-->
                         </div>
                     {% endfor %}
                  {% endif %}

                   <form method="post">
                     {% csrf_token %}
                     {% for field in form %}
                         <p>
                            {{ field.label_tag }}<br>
                            {{ field }}
                            {% if field.help_text %}
                                <small style="color: grey">{{ field.help_text }}</small>
                            {% endif %}
                            {% for error in field.errors %}
                                <p style="color: red"> {{ error }}</p>
                            {% endfor %}
                          </p>
                     {% endfor %}
                     <button type="submit">Değişiklikleri Kaydet</button>
                 </form>
             </div>
        </main>
        </div>
        <!--section -->
{% endblock %}

user/templates/content_gallery.html
<!DOCTYPE html>

<html lang="en">

<head>
    <meta charset="utf-8">
    <title>İçerik Galerisi</title>
</head>


<body>
    <h2>{{ content.title }}</h2>
    <hr>
     {% if messages %}  <!--sistem mesajları böyle kullanılır eğer bir mesaj varsa mesajın türüne göre ekrana yazıyor-->
       {% for message in messages %}
         <div class="aler aler-{{ message.tags }}" role="alert">
           {{ message|safe  }}  <!--Bu uyarılar html tagları içeiryor bu yüzden safe yazdık-->
         </div>
       {% endfor %}
     {% endif %}

     <form method="POST" enctype="multipart/form-data"> <!--formda upload olacağı için multipart yapıyoruz-->
         {% csrf_token %}
         <input type="hidden" name="content_id" id="id_content_id" value="{{ content_id }}">
         <label for="id_title">Başlık:</label>
         <input type="text" name="title" class="input" placeholder="title" maxlength="50"  id="id_title"></p>
         <label for="id_image">Image</label>
         <input type="file" name="image" class="input" placeholder="image" accept="image/*"  id="id_image"></p>
         <button class="primary-btn" type="submit">Resim Yükle</button>
     </form>

    <hr>
    <h4>Yüklenen resimler</h4>
    {% for rs in images %}
        <img src="{{rs.image.url}}" height="200">
    {% endfor %}


</body>
</html>

user/templates/user_addcontent.html
{% extends "homebase.html" %} #burada diyorum ki ben bu sayfada homebase bağlı çalışacağım

{% block title %} {{ profile.user_name }} İçerik Ekle {% endblock %}  #title olan bloğa bunu yaz
{% block keywords %} {{ setting.keywords }} {% endblock %}
{% block description %} {{ setting.description }} {% endblock %}

{% block head %}
    <link rel='shortcut icon' type="image/x-icon"  href="{{setting.icon.url}}" />
    {% load static %}
<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>
<script type="text/javascript" src="{% static 'ckeditor/ckeditor-init.js' %}"></script>
<script type="text/javascript" src="{% static 'ckeditor/ckeditor/ckeditor.js' %}"></script> <!--çalışabilmesi için home/static sayfasına ckeditor4 dosyası yüklendi-->
{% endblock %}



{% block content %}
        <!-- BREADCRUMB -->
         <div id="breadcrumb" class="hoc clear">

           <ul>
              <li><a href="/">Anasayfa</a></li>
               <li><a class="active">Kullanıcı İçerik Ekleme</a></li>
            </ul>

          </div>
        </div>
        <!-- /BREADCRUMB-->

        <!--section -->
           <div class="wrapper row3">
             <main class="hoc container clear">
                 <div class="one_quarter">
                      {% include "user_panel.html" %}
                 </div>
                 <div class="two_quarter">
                     <h6 class="heading">İçerik Ekle</h6>
                           <form method="POST" enctype="multipart/form-data"> <!--formda upload olacağı için multipart yapıyoruz-->
                                 {% csrf_token %}
                                    <fieldset class="from-group">
                                        {{ form.media }} <!-- ckeditor ayarlarını getirir =>yukarıdaki son iki satır buna denk gelir-->
                                        {{ form.as_p }}
                                    </fieldset>
                                    <div class="form-group">
                                        <button class="primary-btn" type="submit">Kaydet</button>
                                    </div>
                           </form>
                 </div>
            </main>
        </div>
        <!--section -->
{% endblock %}

user/templates/user_comments.html
{% extends "homebase.html" %} #burada diyorum ki ben bu sayfada homebase bağlı çalışacağım

{% block title %} {{ profile.user_name }} Yorumlar {% endblock %}  #title olan bloğa bunu yaz
{% block keywords %} {{ setting.keywords }} {% endblock %}
{% block description %} {{ setting.description }} {% endblock %}

{% block head %}
    <link rel='shortcut icon' type="image/x-icon"  href="{{setting.icon.url}}" />
{% endblock %}



{% block content %}
        <!-- BREADCRUMB -->
         <div id="breadcrumb" class="hoc clear">

           <ul>
              <li><a href="/">Anasayfa</a></li>
               <li><a class="active">Kullanıcı Yorumları</a></li>
            </ul>

          </div>
        </div>
        <!-- /BREADCRUMB-->

        <!--section -->
           <div class="wrapper row3">
             <main class="hoc container clear">
                 <div class="one_quarter">
                      {% include "user_panel.html" %}
                 </div>
                 <div class="two_quarter">
                     <h6 class="heading">Kullanıcı Yorum Listesi</h6>
                      <div class="one_third first">
                      </div>
                      <br><br>
                          <div class="scrollable">
                            <table>
                                <tr>
                                  <th>İçerik</th>
                                  <th>Başlık</th>
                                  <th>Yorum</th>
                                  <th>Durum</th>
                                  <th>Tarih</th>
                                  <th></th>
                                </tr>
                                {% for rs in comments %}
                                <tr>
                                  <td><a href="/content/{{ rs.content_id }}/{{ rs.content.slug }}">{{ rs.content.title }}</a></td>
                                  <td>{{ rs.subject }}</td>
                                  <td>{{ rs.comment }}</td>
                                  <td>{{ rs.status }}</td>
                                  <td>{{ rs.create_at }}</td>
                                  <td><button><a onclick="return confirm('Silmek istediğinize emin misiniz?')" href="/user/deletecomment/{{rs.id}}" class="primary-btn">Sil</a></button></td>
                                </tr>
                                {% endfor %}
                            </table>
                          </div>
                 </div>
            </main>
        </div>
        <!--section -->
{% endblock %}

user/templates/user_contents.html
{% extends "homebase.html" %} #burada diyorum ki ben bu sayfada homebase bağlı çalışacağım

{% block title %} {{ profile.user_name }} İçerikler {% endblock %}  #title olan bloğa bunu yaz
{% block keywords %} {{ setting.keywords }} {% endblock %}
{% block description %} {{ setting.description }} {% endblock %}

{% block head %}
    <link rel='shortcut icon' type="image/x-icon"  href="{{setting.icon.url}}" />
{% endblock %}

{% load static %}


{% block content %}
        <!-- BREADCRUMB -->
         <div id="breadcrumb" class="hoc clear">

           <ul>
              <li><a href="/">Anasayfa</a></li>
               <li><a class="active">Kullanıcı İçerikleri</a></li>
            </ul>

          </div>
        </div>
        <!-- /BREADCRUMB-->

        <!--section -->
           <div class="wrapper row3">
             <main class="hoc container clear">
                 <div class="one_quarter">
                      {% include "user_panel.html" %}
                 </div>
                 <div class="two_quarter">
                     <h6 class="heading">Kullanıcı İçerik Listesi</h6>
                      <div class="one_third first">
                         <button><a href="/user/addcontent" class="primary-btn">İçerik Ekle</a></button>
                      </div>
                      <br><br>
                          <div class="scrollable">
                            <table>
                                <tr>
                                  <th>Fotoğraf</th>
                                  <th>Başlık</th>
                                  <th>Tip</th>
                                  <th>Menü</th>
                                  <th>Galeri</th>
                                  <th>Durum</th>
                                  <th>Tarih</th>
                                  <th>Düzenle</th>
                                  <th>Sil</th>
                                </tr>
                                {% for rs in contents %}
                                <tr>
                                  <td><a href="/content/{{ rs.id }}/{{ rs.slug }}"><img src=" {{ rs.image.url }} " style="height:30px;"></a></td>
                                  <td><a href="/content/{{ rs.id }}/{{ rs.slug }}">{{ rs.title }}</a></td>
                                  <td>{{ rs.type }}</td>
                                  <td>{{ rs.menu.title }}</td>
                                  <td><a href="javascript:;" onclick="window.open('/user/contentaddimage/{{rs.id}}', 'gallery', 'height=600,width=800,top=50,left=150')">
                                      <img src="{%static 'images/photo-gallery-icon.png' %}" style="height:30px;">
                                  </a></td>
                                  <td>{{ rs.status }}</td>
                                  <td>{{ rs.create_at }}</td>
                                  <td><button><a href="/user/contentedit/{{rs.id}}" class="primary-btn">Düzenle</a></button></td>
                                  <td><button><a onclick="return confirm('Silmek istediğinize emin misiniz?')" href="/user/contentdelete/{{rs.id}}" class="primary-btn">Sil</a></button></td>
                                </tr>
                                {% endfor %}
                            </table>
                          </div>
                 </div>
            </main>
        </div>
        <!--section -->
{% endblock %}

user/templates/user_panel.html
    <div class="sidebar  first">
      <h6>Kullanıcı Paneli</h6>
      <nav class="sdb_holder">
        <ul>
          <li><a href="/user">KULLANICI PROFİLİ</a></li>
          <li><a href="/user/contents">İÇERİKLERİM</a></li>
          <li><a href="/user/comments">YORUMLARIM</a></li>
          <li><a href="/logout">ÇIKIŞ</a></li>
        </ul>
      </nav>
    </div>